# Project
modVersion=9.1.6.0
mavenGroup=com.github.teamfossilsarcheology.fossils-archeology-revival
archivesName=fossils-archeology-revival

# Common
minecraftVersion=1.20.1
minecraftVersionRange=[1.20,1.20.1)
parchmentDate=2023.09.03
enabledPlatforms=quilt,fabric,forge

# Mod options
modId=fossil
modName=Fossils and Archeology: Revival
modTeam=TeamFossilsArcheology
modLicense=Code: Mit, Assets: ARR
modDescription=Adding dinosaurs, fossils, and more to Minecraft.
modAuthors= DarkPred, DDinoDan, Dipple_Effect, Indominator, Javaraptor, Robberto08, SealManVI, TotallyNotAHobo, \
  Totemaster, 4f6f3b, Alexthe666, ASDFGirlS7, Blue, JTGhawk137, gegy1000, tmvkrpxl0, tyranno66

# Dependencies
fabricLoaderVersion=0.16.14
terraBlenderVersion=3.0.1.10
moreHitboxesVersion=1.9.0
reiVersion=12.1.785
architecturyVersion= 9.2.14

archivesBaseName=fossil

org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.daemon=true
